name: photo_watermark
description: Aplique uma ou várias logos em lote nas suas fotos (iOS e Android).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  image: ^4.2.0
  gal: ^2.3.0
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
